### ISSUE TITLE
touch strum not working on iOS

### ISSUE THREAD

**Issue by xmeatballx** [jakealbaugh/omnichord#1]
![Screen Shot 2022-02-07 at 7 25 10 PM](https://user-images.githubusercontent.com/59705488/152894647-d8238d2c-c82d-4921-9d1e-44d27e69f75b.png)
~~get this error on iOS simulator safari dev tools. appears to be related to the index handling in the handleStepper function in controller.js. Will fork and try to provide more details~~

EDIT:
actually an issue with Tone.PingPongDelay(). I'm guessing it is an issue with stereo audio effect support on iOS??? since the error log references a non-existent output index. But all strum issues are resolved when Tone.PingPongDelay is disconnected from the signal flow

**Comment by ja-k-e** [comment]
this may be fixed by https://github.com/jakealbaugh/omnichord/commit/a2ab3ace1460d6eaf3f78e2e7dd5c3dfbcd1efcc. had to do with initialization potentially leading to multiple invocations of Tone.start() and calling on `connect()` before Tone was initialized. Thank you!! Let me know if this isn't resolved.

**Comment by xmeatballx** [comment]
Still getting the same error on init. It's just hanging on the loading... state
![Screen Shot 2022-02-07 at 8 55 02 PM](https://user-images.githubusercontent.com/59705488/152903079-f564f2b2-0ba4-47d6-a31a-dbe2f86ad206.png)

**Comment by ghost** [comment]
yeah, stuck on loading everywhere except in chrome desktop and safari/webkit desktop
